gems: [jekyll-paginate]

# General
name: 173210's Blog
url: https://173210.github.io

highlighter: rouge

paginate: 5
permalink: /:title

# Social share and comments.
twitter: 173210
github: 173210
google: +101584445317725784159

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
