# General
name: 173210's Blog
description: "How will you describe my blog? Please tell me on twitter or email."
url: http://173210.github.io

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
twitter: 173210
github: 173210
google: +101584445317725784159

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
